# permissions for end users to view tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-viewer-role
rules:
- apiGroups:
  - qiniu.com
  resources:
  - tests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qiniu.com
  resources:
  - tests/status
  verbs:
  - get
