# permissions for end users to edit qvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qvm-editor-role
rules:
- apiGroups:
  - qiniu.com.qiniu.com
  resources:
  - qvms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qiniu.com.qiniu.com
  resources:
  - qvms/status
  verbs:
  - get
