# permissions for end users to view qvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qvm-viewer-role
rules:
- apiGroups:
  - qiniu.com.qiniu.com
  resources:
  - qvms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qiniu.com.qiniu.com
  resources:
  - qvms/status
  verbs:
  - get
